### ISSUE TITLE
找不到snli_label_desp.txt

### ISSUE THREAD

**Issue by Josoope** [little1tow/DELE_pytorch#2]
运行main.py文件后，报错FileNotFoundError: [Errno 2] No such file or directory: 'dataset/sentence_pair\\snli\\origin_file\\snli_label_desp.txt'
下载的数据集里没有snli_label_desp.txt，请问怎么解决呀

**Comment by Josoope** [comment]
label_desp.txt问题解决了，现在出现这个错误File "D:\pythondata\DELE_pytorch-main\model.py", line 70, in __init__
    self.label_semantic_atten = ph.nn.MLPAttention(
AttributeError: module 'photinia' has no attribute 'nn'
photinia这个库的信息太少了，没找到解决方案

**Comment by Zhoufj8** [comment]
> label_desp.txt问题解决了，现在出现这个错误File "D:\pythondata\DELE_pytorch-main\model.py", line 70, in **init** self.label_semantic_atten = ph.nn.MLPAttention( AttributeError: module 'photinia' has no attribute 'nn' photinia这个库的信息太少了，没找到解决方案

请问snli 1.0 test_hard那个文件你找到了吗

**Comment by Zhoufj8** [comment]
> label_desp.txt问题解决了，现在出现这个错误File "D:\pythondata\DELE_pytorch-main\model.py", line 70, in **init**
> self.label_semantic_atten = ph.nn.MLPAttention(
> AttributeError: module 'photinia' has no attribute 'nn'
> photinia这个库的信息太少了，没找到解决方案

可以去pypi下载，把文件后缀.whl换成.zip解压之后就能看到源码了，自己用pytorch写一个其实更快，使用photinia这个库它想要实现的是一个很普通的加性注意力，MLPAttention是在att.py这个文件中
